### ISSUE TITLE
Generate ExecFlow input files from OntoFlow output

### ISSUE THREAD

**Issue by jesper-friis** [H2020-OpenModel/OntoFlow#7]
# Model documentation
OntoFlow works on a knowledge base that is populated with existing data sources and models. In order to generate input files to execflow, we should document the datasources as OTEAPI partial pipelines.

To document a model or simulation tool we must documents its:
- **input**: documented as OTEAPI partial pipeline for a data sink (input in the form expected by the model)
- **output**: documented as OTEAPI partial pipeline for a data source (output generated by the model)
- **execution**: how to execute the model

For documenting the model execution, we will for simplicity (initially) assume that the model exists as executable already installed on the system in a directory included in the users `PATH` environment variable. This way we can refer to the executable just by its name, getting rid of issues with absolute paths that will differ between users. If an absolute path is needed, it can easily be obtained with the `which` shell command (or `shutil.which()` in Python).

The model execution may also contain some information additional information for setting up the right environment, like:
- arguments
- needed environment variables
- standard input (as OTEAPI partial pipeline for a data sink)
- standard output (as OTEAPI partial pipeline for a data source)
- standard error (as OTEAPI partial pipeline for a data source)
- ...

Support for these can be added with time. Initially we can probably skip these.

## Populating the knowledge base
We need an easy way to populate the knowledge base with the above information. The easiest is probably a simple YAML format. Templating facilities can be added as a separate pre-processing step to e.g. make it easy to document many similar data sources. 

A suggested YAML syntax
```yaml
---
version: 1.0

# Prefixes may be optional
prefixes:
  "": http://openmodel.eu/resources/data#  # base IRI
  ex: http://example.com/ex#
  temp: http://openmodel.eu/resources/data/temperature-20240228.csv#

data_resources:  # partial_pipelines

  # Documentation of a data source
  :temperature_measurement:  # could consider to make the prefix/initial colon optional
    dataresource:
      description: Measurement of outdoor temperature  in Bristol during one day.
      wasGeneratedBy: ex#termometer_XJ45
      downloadURL: http://openmodel.eu/resources/data/temperature-20240228.csv
      mediaType: text/csv
    parse:
      parserType: dlite-parse
      datamodel: http://onto-ns.com/meta/openmodel/0.1/Temperature
      configurations:
        driver: csv
    mapping:
      mappingType: mappings
      triples:
        - temp#temperature map:mapsTo emmo:Temperature

  # Documentation of a data sink
  :mean_temperature
    mapping:
      ...
    generate:
      ...
    dataresource:
      ...

  # Documentation of a model
  :my_model:
    model:  # alternative labels could be transformation, function, ...
      description: A model that calculates the mean temperature
      modelType: executable
      executable:
        command: meantemp
        environment:
          MEANTEMP_MODE: cold 
      inputs:
        - ex:temperature_measurement
      outputs:
        - ex:mean_temperature

```

# Templating
To be decided. It would be smart if we could use an existing [pre-processing language](https://en.wikipedia.org/wiki/Preprocessor), like cpp or m4. Probably there exists something better suited for our purposes.
